### ISSUE TITLE
upgrade image mongodb readonly

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#3224]
The image for `mongodb_read_only` uses v3.0 which is not supported anymore. This needs to be upgraded to a version we support.

```
  quasar_mongodb_read_only:
    container_name: quasar_mongodb_read_only
    image: mongo:3.0
    command: mongod --smallfiles
    ports:
      - "27020:27017"
```
